django_common/urls.py
from django.contrib import admin
from django.urls import path , include 

admin.site.site_header = "Movies app"
admin.site.site_title = "Movies Admin Portal"
admin.site.index_title = "Welcome to Service Provider Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('', include('movies.urls')), #adding path for main app urls file
]

movies/urls.py
from . import views

from django.urls import include, path
from rest_framework import routers
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView # new
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from rest_framework.routers import DefaultRouter
from movies.views import signUp
from movies.form import RequestForm


app_name = "movies"

router = DefaultRouter()
# router.register('login_api', LoginAPI, basename = 'login_api')

urlpatterns = [
#     path('admin/', admin.site.urls),
    
    path('rest_api', include(router.urls)), 
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
    #path('login', views.login),
#     path('logout', views.logout_view), 
    path("register/", views.signup, name="register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', signUp.as_view(), name = 'signup'),
    path('movie_list',views.movieList,name = 'movie_list'),
    path('wishlist',views.wishList,name = 'wishlist'),
    path('user',csrf_exempt(views.userLogin),name = 'user'),
    
    path('service_request/', views.serviceRequest, name='service_request'), # new
    path('view_service_request/', views.ViewSevice, name='view_service_request'), # new
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',success_url = reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
    path('movie_search',views.movieSearch,name = 'movie_search')
]

movies/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField


class Movies(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    rating = models.FloatField()
    image_url = models.URLField(max_length=1000)
    redirect_url = models.URLField()
    
    
class MovieWishlist(models.Model):
    username = models.CharField(max_length=100)
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE, null=True)


class UserData(models.Model):
    user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField(blank=True, max_length=255,null= True)
    firebase_id = models.CharField(max_length=255,blank = True)
    dob = models.DateField(blank = True, null= True)
    email_id = models.EmailField(max_length=254,blank = True,null= True)
    phone_number = models.IntegerField(blank=True,null= True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)


class ServiceRequest(models.Model):
    STATUS_OPTION = (
                    ('Pending', 'Pending'),
                    ('In Progress', 'In Progress'),
                    ('Completed', 'Completed'),
                    )
    username = models.CharField( max_length=255)
    request_type = models.CharField( max_length=255)
    request_desc = models.TextField()
    city = models.CharField(max_length=254,blank = True,null= True)
    state = models.CharField( max_length=255)
    pin_code = models.IntegerField()
    phone_code = models.CharField(blank=True, max_length=3,null= True)
    alternate_phone_number = models.IntegerField(blank=True,null= True)
    status = models.CharField(max_length=255,blank = True,null= True, choices=STATUS_OPTION, default='Pending', editable=True)
    remarks = models.TextField(blank = True,null= True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_by = models.CharField( max_length=255,blank = True,null= True)
    

movies/views.py
from django.shortcuts import render, redirect
from .serializers import UserSerializer,User_register,MoviesSerializer,WishlistSerializer,MoviesSerializer1
from .models import Movies,MovieWishlist, UserData, ServiceRequest
from .form import NewUserForm, SignUpForm , RequestForm
    
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from bs4 import BeautifulSoup
import requests
import json
from rest_framework import status, serializers
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions
from rest_framework.permissions import AllowAny
from rest_framework.authtoken.models import Token
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)
from rest_framework.pagination import PageNumberPagination

from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth import login as auth_login, logout, authenticate
from django.contrib import messages


@api_view(['POST','GET'])
@permission_classes((AllowAny,))
def sample_api(request):
    if request.method == 'GET':
        data = {'sample_data get method': 123}
        return Response(data, status=HTTP_200_OK)

    elif request.method == 'POST':
        data = {'sample_data post method': 123}
        return Response(data, status=HTTP_200_OK)


class signUp(APIView):
    permission_classes = [AllowAny]
    def post(self, request, format=None):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            content = {
            'status': 'Thanks for registering'}
            return Response(content, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["POST"])
@permission_classes((AllowAny,))
def login(request):
    username = request.data.get("username") 
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_400_BAD_REQUEST)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)  
    


@api_view(["POST","GET"])
# @permission_classes((AllowAny,))
def movieList(request):
    user = request.user
    movie_id = request.query_params.get('id')
    movie_title = request.query_params.get('title')
    if request.method == 'GET':
        paginator = PageNumberPagination()
        paginator.page_size = 10
        context = {"username": user}
        
        if movie_id or movie_title:
            try:
                if movie_id:
                    movies_obj = Movies.objects.get(id=movie_id)
                else:
                    movies_obj = Movies.objects.get(title=movie_title)
                serializer = MoviesSerializer1(movies_obj,context=context, many=False)
                return Response(serializer.data)
            except Movies.DoesNotExist:
                movies_obj = None
        else:
            movies_obj = Movies.objects.all()
            result_page = paginator.paginate_queryset(movies_obj, request)
            serializer = MoviesSerializer1(result_page,context=context, many=True)
        if movies_obj == None:
           return Response({'error': 'Please provide valis movie id or title'},
                        status=HTTP_400_BAD_REQUEST) 
        return paginator.get_paginated_response(serializer.data)
    
    if request.method == 'POST':
        """url= 'https://www.imdb.com/chart/top/'
           url = 'https://www.imdb.com/india/top-rated-indian-movies/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=461131e5-5af0-4e50-bee2-223fad1e00ca&pf_rd_r=6SSJ32D3EGD0SPY3SS7E&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=india.toprated&ref_=fea_india_ss_toprated_india_tr_india250_hd'
        """
        scrap_url = request.data.get("scrap_url") 
        if scrap_url is None:
            return Response({'error': 'Please provide scrap url'},
                            status=HTTP_400_BAD_REQUEST)
        response_data = requests.get(scrap_url)
        soup = BeautifulSoup(response_data.text, 'html.parser')
        mydivs = soup.findAll("tbody", {"class": "lister-list"})[0].findAll("tr")
        for each in mydivs:
            image_url = each.findAll("td",{"class":"posterColumn"})[0].find('a').img['src']
            title = each.findAll("td",{"class":"titleColumn"})[0].find('a').text
            redirect_tag = each.findAll("td",{"class":"titleColumn"})[0].find('a')['href']
            redirect_url = 'https://www.imdb.com'+redirect_tag
            year = (each.findAll("td",{"class":"titleColumn"})[0].find('span').text)[1:5]
            rating = each.findAll("td",{"class":"ratingColumn imdbRating"})[0].find('strong').text
            
            obj, created = Movies.objects.update_or_create(title=title,
                                                           year=int(year),
                                                           rating=rating,
                                                           image_url=image_url,
                                                           redirect_url=redirect_url)

        return Response({'result': "successfully saved"},
                        status=HTTP_200_OK) 
    
  
 
@api_view(["GET","POST","DELETE"])
# @permission_classes((AllowAny,))
def wishList(request):
    user = request.user
    
    if request.method == 'GET':
        wishlist_obj = MovieWishlist.objects.filter(username=user)
        if wishlist_obj:
            serializer = WishlistSerializer(wishlist_obj, many=True)
            return Response(serializer.data) 
        else:
            return Response({'result': "no records found"},
                        status=HTTP_200_OK) 
    
    if request.method == 'POST':
        movie_id = request.data.get("movie_id")
        obj, created = MovieWishlist.objects.update_or_create(movie_id=movie_id,
                                                              username = user
                                                              )
        return Response({'result': 'wishlist saved'},
                        status=HTTP_200_OK) 
    
    if request.method == 'DELETE':
        wishlist_id = request.data.get("wishlist_id")
        try:
            wishlist_row = MovieWishlist.objects.get(id=wishlist_id)
        except MovieWishlist.DoesNotExist:
            wishlist_row = None
        if wishlist_row == None:
            return Response({'error': 'Please provide valid wishlist id'},
                        status=HTTP_400_BAD_REQUEST)
        wishlist_row.delete()
        return Response({'result': 'successfully deleted'},
                        status=HTTP_200_OK) 
  
 
@api_view(["GET"])
# @permission_classes((AllowAny,))
def movieSearch(request):
    user = request.user
    movie_title = request.query_params.get('title')
    if request.method == 'GET':
        try:
            movie_row = Movies.objects.filter(title__icontains=movie_title)
        except Movies.DoesNotExist:
            movie_row = None
        if movie_row:
            context = {"username": user}
            serializer = MoviesSerializer1(movie_row,context=context, many=True)
            return Response(serializer.data)
        else:
            return Response({'result': "no record found"},
                        status=HTTP_200_OK) 
    
 
@api_view(["POST"])
@permission_classes((AllowAny,))
def userLogin(request):
    json_data=json.loads(request.body)
    firebase_id = json_data.get("firebase_id")
    username = json_data.get("username")
    email_id = json_data.get("email_id")
    
    if firebase_id is None or email_id is None:
        return Response({'error': 'Please provide correct firebase id and email id'},
                        status=HTTP_400_BAD_REQUEST)
    try:
        user_row = User.objects.get(username=username)
    except User.DoesNotExist:
        user_row = None
    
    if user_row is not None:
        token, _ = Token.objects.get_or_create(user=user_row)
        data = {'token': token.key,'username':username,'email_id':email_id}
        return JsonResponse({'result':'SUCCESS','data':data,'message': 'Logged in successfully'},
                    status=HTTP_200_OK)
    else:
        print("pradeep2")
        user_row, _ = User.objects.get_or_create(username=username)
        user_data= UserData(firebase_id=firebase_id,email_id=email_id,username=username).save()
        token, _ = Token.objects.get_or_create(user=user_row)
        data = {'token': token.key,'username':username,'email_id':email_id}
        return JsonResponse({'result':'SUCCESS','data':data,'message': 'Logged in successfully'},
                    status=HTTP_200_OK)
    
#     user = authenticate(username=username, password=password)
#     if not user:
#         return Response({'error': 'Invalid Credentials'},
#                         status=HTTP_400_BAD_REQUEST)
#     token, _ = Token.objects.get_or_create(user=user)
#     return Response({'token': token.key},
#                     status=HTTP_200_OK)   
 
 
 


def logout_view(request):
    logout(request)
    return redirect('/')
 

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        print("pradeep")
        if form.is_valid():
            print("pradeep1")
            user = form.save()
            username = form.cleaned_data.get('username')
            print(username)

movies/templates/ user_created_news.html
<form action="/" method="post" style="margin:left=50px; margin:right=20px;">
    {% csrf_token %}
	<div class="form-group">
    	<label for="user_name">User Name</label>
    	<input type="text" class="form-control" id="user_name" type="text" name="user_name" placeholder="user_name input">
    </div>
    <div class="form-group">
    	<label for="location">Enter Your Location</label>
    	<input type="text" class="form-control" id="location" name="location" >
  	</div>

  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
  </div>
  	 <div class="form-group">
    	<label for="title">Enter Title</label>
    	<input type="text" class="form-control" id="title" name="title"  >
  	</div>

  <div class="form-group">
    <label for="description">Enter Your Content</label>
    <textarea class="form-control" id="description" type="text" name="description" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

movies/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Sample App{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

movies/templates/header.html
<div class="header">
    	    <div class="header-left" >
        	    <li style="padding-left:5%;"><a routerLink="#"  >psd</a></li>
            </div>
        	<div class="header-right" style="padding-top:1.5%;font-size:150%;" > 
            	<li style="padding-left:10%;" ><a routerLink="#"  >Home</a> </li>  
            	<li style="padding-left:3%;" ><a routerLink="#"  >About</a> </li>
            	<li style="padding-left:3%;" ><a routerLink="#"  >Events</a> </li>
            	<li style="padding-left:3%;"  ><a routerLink="#"  >Contact_Us</a> </li>
            	<li style="padding-left:3%;" ><a routerLink="#"  >SignUp</a> </li>
            	<li style="padding-left:3%; " ><a routerLink="#"  >Login</a> </li>
        	</div>
       </div>

movies/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	<div style = "display: flex;margin-bottom:200px">
    	<div style = "text-align:left; width:80%; "><b>Welcome</b> <span style="color:blue;font-size: 200%;"><b>{{ user.username }}!</b></span></div>
		<div style="text-align:right;  float:right;width:80%;font-size: 150%; "><a href="{% url 'movies:logout' %}">Logout</a></div>
	</div>
	<div style = "display: flex;margin:300px;align: center; border:solid; padding:80px;">
		<div style="text-align:center;  float:right;width:50%;font-size: 150%; "> <a href="{% url 'movies:service_request' %}"> Add New Request </a> </div>
		<div style="text-align:center;  float:right;width:50%;font-size: 150%; "> <a href="{% url 'movies:view_service_request' %}"> View Your Requests </a> </div>
	</div>

{% else %}
<div style="align:center;margin-top:300px;margin-bottom:300px;margin-left:40%;">
  <p style="font-size:40px;">You are not logged in</p>
  <button style="margin-left:60px;font-size:20px;"><a href="{% url 'movies:login' %}">Login</a></button>
  <button style="margin-left:50px;font-size:20px;"><a href="{% url 'movies:register' %}">Register</a></button>
</div>
{% endif %}
{% endblock %}

movies/templates/homepage.html
<html >
	<head>
		<title>Home-Page</title>
		
				
	</head>
	<body style="background-color: #DDDDDD;">
		{% include "header.html" %}
		
		<div style="padding-top:20px;position:relative;"></div>
		
		       
		<div  style="padding-left:200px;padding-right:200px;padding-top:5%;">
			
		
		</div>
<div style="padding-left:200px;padding-right:200px;">
	
	</div>	
		
       
		
	</body>
</html>

movies/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'django.contrib.auth.views.login' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

movies/templates/register.html
{% block content %}
    <form method="POST">
    	{% csrf_token %}
    	 {{form.as_p}}
    	 <button class="btn" type="submit" >signUp </button>
    </form>	 
   if you already have an account, <a href="/login"><strong>LOGIN</strong></a>
{% endblock %} 

movies/templates/service_request_form.html
{% extends 'base.html' %}

{% block title %}add New service Request{% endblock %}

{% block content %}
	{% if msg %}
		<h2 style = "margin-bottom:50px;">Hi <span style="color:blue;font-size: 150%;">{{ user.get_username }}</span>, You request has been recieved successfully.</h2>
		<div>
		   <div><p style= "text-align:center;"><button style= "margin-top:20px;padding-left:40px;padding-right:40px;font-size:25px;background-color:#0000FF;-webkit-border-radius:28px;-moz-border-radius:28px;"> <a style="color:white;text-decoration: none;" href="{% url 'movies:service_request' %}"> New Request </a> </button></p></div>
		   <div><p style= "text-align:center;"><button style= "margin-top:20px;padding-left:40px;padding-right:40px;font-size:25px;background-color:#0000FF;-webkit-border-radius:28px;-moz-border-radius:28px;"> <a style="color:white;text-decoration: none;" href="{% url 'movies:home' %}"> Go Homepage </a> </button></p></div>
		   <div><p style= "text-align:center;"><button style= "margin-top:20px;padding-left:40px;padding-right:40px;font-size:25px;background-color:#0000FF;-webkit-border-radius:28px;-moz-border-radius:28px;"> <a style="color:white;text-decoration: none;" href="{% url 'movies:view_service_request' %}"> View Your Requests </a> </button></p></div>
		</div>
	{% else %}
	
  <h2 style = "margin-bottom:50px;"><span style="color:blue;font-size: 150%;">{{ user.get_username }}</span> Please fill below details for your request</h2>
  

  <div style="margin:50px;">
  	<form method="POST">
    	{% csrf_token %}
    	<table style="border:solid;">
    		{% for field in form %}
    			<tr style= "margin:100px;border:solid">
 					<td style= "align-text:left;" >
        				<b>{{ field.label_tag }}</b>
        			</td>
        			<td >
        				{% if "request_type" == field.name %}
        					{% for i in field %}
        			 			{{i}}
        					{% endfor %}
        				{% else %}
        					{{field}}
        				{% endif %}
        			</td>
        		</tr>	
        		{% if field.help_text %}
        			<small style="color: grey">{{ field.help_text }}</small>
        		{% endif %}
        		{% for error in field.errors %}
        		  <p style="color: red">{{ error }}</p>
        		{% endfor %}
    		{% endfor %}
    		
    	</table>
    	<div style="margin:50px;margin-left:150px;">
    		<button style= "color:white;margin-top:20px;padding-left:40px;padding-right:40px;font-size:25px;background-color:#0000FF;-webkit-border-radius:28px;-moz-border-radius:28px;" type="submit">Submit</button>
    	</div>
  	</form>
  	{% endif %}
  </div>
{% endblock %}

movies/templates/signup.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
    	{% if "username" == field.name %}

    	{% else %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        
      </p>
      {% endif %}
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

movies/templates/view_service_request.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Request lists{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <h2 style = "margin-bottom:30px;">Hi <span style="color:blue;font-size: 150%;">{{ user.get_username }}</span>, Please check your request and it's status ! </h2>
  	{% if content %}

	<table style = "font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;">
  		<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
    		<th>Request Id</th>
    		<th>Request Type</th>
    		<th>Request Desc</th>
    		<th>Request date</th>
    		<th>status</th>
    		<th>Detailed status</th>
  		</tr>
  		
  		{% for field in content %}
  		<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  			<td>{{field.id}}</td>
    		<td>{{field.request_type}}</td>
    		<td>{{field.request_desc}}</td>
    		<td>{{field.created_at}}</td>
    		<td>{{field.status}}</td>
    		<td><a href="{% url 'movies:view_service_request'%}?data={{field.id}}"> Click </a></td>
  		</tr>
  		{% endfor %} 
  		</table>
  		<p style= "text-align:center;"><button style= "margin-top:20px;padding-left:40px;padding-right:40px;font-size:25px;background-color:#0000FF;-webkit-border-radius:28px;-moz-border-radius:28px;"> <a style="color:white;text-decoration: none;" href="{% url 'movies:service_request' %}"> New Request </a> </button></p>
  		
  	{% elif content_by_id %}
		<div>  
			<table style = "font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;">	
  				<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Request type</th>
    				<td>{{content_by_id.request_type}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Request Desc</th>
    				<td>{{content_by_id.request_desc}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>City</th>
    				<td>{{content_by_id.city}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>State </th>
    				<td>{{content_by_id.state}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Pin Code</th>
    				<td>{{content_by_id.pin_code}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Alternate Phone Number</th>
    				<td>{{content_by_id.phone_code}}-{{content_by_id.alternate_phone_number}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Status</th>
    				<td>{{content_by_id.status}}</td>
    			</tr>
    			<tr style = "border: 1px solid #dddddd;  text-align: left;  padding: 8px;">
  					<th>Remarks</th>
    				<td>{{content_by_id.remarks}}</td>
    			</tr>
  			</table>
  		</div>
		<p> <a href="{% url 'movies:view_service_request'%}"> Back </a> </p>
  		
  	{% else %}
  		<p> You dont't have any requested service to view. You can add using below click
  		<p> <a href="{% url 'movies:service_request' %}"> New Request </a> </p>
  	{% endif %}
{% endif %}
{% endblock %}